[2025-03-09T17:18:26.448+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T17:18:26.488+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T17:17:17.551467+00:00 [queued]>
[2025-03-09T17:18:26.507+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T17:17:17.551467+00:00 [queued]>
[2025-03-09T17:18:26.509+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T17:18:26.727+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_transform> on 2025-03-09 17:17:17.551467+00:00
[2025-03-09T17:18:26.740+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T17:18:26.742+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2025-03-09T17:18:26.743+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_etl_orchestration', 'trigger_transform', 'manual__2025-03-09T17:17:17.551467+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpcf5sceqs']
[2025-03-09T17:18:26.745+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask trigger_transform
[2025-03-09T17:18:26.827+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T17:17:17.551467+00:00 [running]> on host 72a6d77a3cc5
[2025-03-09T17:18:26.963+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_etl_orchestration' AIRFLOW_CTX_TASK_ID='trigger_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T17:17:17.551467+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T17:17:17.551467+00:00'
[2025-03-09T17:18:26.965+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T17:18:26.966+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T17:18:26.967+0000] {logging_mixin.py:190} INFO - Current task name:trigger_transform state:running start_date:2025-03-09 17:18:26.489720+00:00
[2025-03-09T17:18:26.967+0000] {logging_mixin.py:190} INFO - Dag name:tiki_etl_orchestration and current dag run status:running
[2025-03-09T17:18:26.968+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T17:18:27.084+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-09 17:18:26.969664+00:00 to become allowed state ['success'] ...
[2025-03-09T17:18:37.118+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-09T17:18:37.126+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T17:18:37.127+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 17:18:26.489720+00:00 end:2025-03-09 17:18:37.125959+00:00 duration:10.636239
[2025-03-09T17:18:37.128+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_transform> dag:<DAG: tiki_etl_orchestration> dagrun:<DagRun tiki_etl_orchestration @ 2025-03-09 17:17:17.551467+00:00: manual__2025-03-09T17:17:17.551467+00:00, state:running, queued_at: 2025-03-09 17:17:18.135066+00:00. externally triggered: True>
[2025-03-09T17:18:37.129+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-09T17:18:37.129+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_etl_orchestration, task_id=trigger_transform, run_id=manual__2025-03-09T17:17:17.551467+00:00, execution_date=20250309T171717, start_date=20250309T171826, end_date=20250309T171837
[2025-03-09T17:18:37.190+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T17:18:37.191+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 235 for task trigger_transform (tiki_transform_dag failed with failed states failed; 103)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-09T17:18:37.237+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T17:18:37.291+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T17:18:37.300+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
