[2025-03-09T12:13:45.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T12:13:45.669+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_transform_dag.transform_data manual__2025-03-09T12:13:42.450162+00:00 [queued]>
[2025-03-09T12:13:45.688+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_transform_dag.transform_data manual__2025-03-09T12:13:42.450162+00:00 [queued]>
[2025-03-09T12:13:45.689+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T12:13:45.715+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-09 12:13:42.450162+00:00
[2025-03-09T12:13:45.728+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T12:13:45.731+0000] {standard_task_runner.py:72} INFO - Started process 156 to run task
[2025-03-09T12:13:45.731+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_transform_dag', 'transform_data', 'manual__2025-03-09T12:13:42.450162+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/tiki_transform_dag.py', '--cfg-path', '/tmp/tmpour_04p9']
[2025-03-09T12:13:45.733+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask transform_data
[2025-03-09T12:13:45.812+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_transform_dag.transform_data manual__2025-03-09T12:13:42.450162+00:00 [running]> on host 117245270d1c
[2025-03-09T12:13:45.974+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_transform_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T12:13:42.450162+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T12:13:42.450162+00:00'
[2025-03-09T12:13:45.977+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T12:13:45.978+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T12:13:45.979+0000] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2025-03-09 12:13:45.670894+00:00
[2025-03-09T12:13:45.980+0000] {logging_mixin.py:190} INFO - Dag name:tiki_transform_dag and current dag run status:running
[2025-03-09T12:13:45.981+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T12:13:46.027+0000] {tiki_transform_dag.py:46} INFO - Transform task running with execution_date: 2025-03-09 12:13:42.450162+00:00
[2025-03-09T12:13:46.048+0000] {tiki_transform_dag.py:54} INFO - Orchestration execution_date from XCom: None
[2025-03-09T12:13:46.049+0000] {tiki_transform_dag.py:58} WARNING - No orchestration_execution_date found. Using current execution_date.
[2025-03-09T12:13:46.050+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_transform_dag.py", line 62, in transform_data
    raw_blob_name = kwargs['ti'].xcom_pull(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'execution_date'
[2025-03-09T12:13:46.085+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T12:13:46.086+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 12:13:45.670894+00:00 end:2025-03-09 12:13:46.084492+00:00 duration:0.413598
[2025-03-09T12:13:46.087+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_data> dag:<DAG: tiki_transform_dag> dagrun:<DagRun tiki_transform_dag @ 2025-03-09 12:13:42.450162+00:00: manual__2025-03-09T12:13:42.450162+00:00, state:running, queued_at: 2025-03-09 12:13:42.510952+00:00. externally triggered: True>
[2025-03-09T12:13:46.088+0000] {logging_mixin.py:190} INFO - Failure caused by TaskInstance.xcom_pull() got an unexpected keyword argument 'execution_date'
[2025-03-09T12:13:46.089+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_transform_dag, task_id=transform_data, run_id=manual__2025-03-09T12:13:42.450162+00:00, execution_date=20250309T121342, start_date=20250309T121345, end_date=20250309T121346
[2025-03-09T12:13:46.582+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T12:13:46.583+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 160 for task transform_data (TaskInstance.xcom_pull() got an unexpected keyword argument 'execution_date'; 156)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_transform_dag.py", line 62, in transform_data
    raw_blob_name = kwargs['ti'].xcom_pull(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'execution_date'
[2025-03-09T12:13:46.671+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T12:13:46.709+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T12:13:46.713+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
