[2025-03-10T09:23:14.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T09:23:14.045+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_transform_dag.transform_data manual__2025-03-10T09:12:56.374235+00:00 [queued]>
[2025-03-10T09:23:14.054+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_transform_dag.transform_data manual__2025-03-10T09:12:56.374235+00:00 [queued]>
[2025-03-10T09:23:14.055+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-03-10T09:23:14.074+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-10 09:12:56.374235+00:00
[2025-03-10T09:23:14.084+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1761) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T09:23:14.086+0000] {standard_task_runner.py:72} INFO - Started process 1763 to run task
[2025-03-10T09:23:14.086+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_transform_dag', 'transform_data', 'manual__2025-03-10T09:12:56.374235+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/tiki_transform_dag.py', '--cfg-path', '/tmp/tmp4_7vyw2_']
[2025-03-10T09:23:14.087+0000] {standard_task_runner.py:105} INFO - Job 382: Subtask transform_data
[2025-03-10T09:23:14.147+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_transform_dag.transform_data manual__2025-03-10T09:12:56.374235+00:00 [running]> on host c77555d100c4
[2025-03-10T09:23:14.691+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_transform_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T09:12:56.374235+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T09:12:56.374235+00:00'
[2025-03-10T09:23:14.693+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T09:23:14.694+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T09:23:14.695+0000] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2025-03-10 09:23:14.045903+00:00
[2025-03-10T09:23:14.695+0000] {logging_mixin.py:190} INFO - Dag name:tiki_transform_dag and current dag run status:running
[2025-03-10T09:23:14.696+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T09:23:15.942+0000] {tiki_transform_dag.py:67} ERROR - No metadata file found in GCS.
[2025-03-10T09:23:15.943+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_transform_dag.py", line 68, in transform_data
    raise ValueError("No metadata file found in GCS.")
ValueError: No metadata file found in GCS.
[2025-03-10T09:23:15.957+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T09:23:15.958+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 09:23:14.045903+00:00 end:2025-03-10 09:23:15.957216+00:00 duration:1.911313
[2025-03-10T09:23:15.958+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_data> dag:<DAG: tiki_transform_dag> dagrun:<DagRun tiki_transform_dag @ 2025-03-10 09:12:56.374235+00:00: manual__2025-03-10T09:12:56.374235+00:00, state:running, queued_at: 2025-03-10 09:12:56.407304+00:00. externally triggered: True>
[2025-03-10T09:23:15.959+0000] {logging_mixin.py:190} INFO - Failure caused by No metadata file found in GCS.
[2025-03-10T09:23:15.959+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_transform_dag, task_id=transform_data, run_id=manual__2025-03-10T09:12:56.374235+00:00, execution_date=20250310T091256, start_date=20250310T092314, end_date=20250310T092315
[2025-03-10T09:23:15.987+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T09:23:15.987+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 382 for task transform_data (No metadata file found in GCS.; 1763)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_transform_dag.py", line 68, in transform_data
    raise ValueError("No metadata file found in GCS.")
ValueError: No metadata file found in GCS.
[2025-03-10T09:23:16.029+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T09:23:16.050+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T09:23:16.052+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
