[2025-03-09T14:34:43.509+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T14:34:43.555+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T14:33:23.378192+00:00 [queued]>
[2025-03-09T14:34:43.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T14:33:23.378192+00:00 [queued]>
[2025-03-09T14:34:43.584+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T14:34:43.900+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_transform> on 2025-03-09 14:33:23.378192+00:00
[2025-03-09T14:34:43.914+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=122) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T14:34:43.918+0000] {standard_task_runner.py:72} INFO - Started process 124 to run task
[2025-03-09T14:34:43.918+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_etl_orchestration', 'trigger_transform', 'manual__2025-03-09T14:33:23.378192+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpv6o01b5s']
[2025-03-09T14:34:43.920+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask trigger_transform
[2025-03-09T14:34:44.019+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T14:33:23.378192+00:00 [running]> on host 10038f9c1f89
[2025-03-09T14:34:44.184+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_etl_orchestration' AIRFLOW_CTX_TASK_ID='trigger_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T14:33:23.378192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T14:33:23.378192+00:00'
[2025-03-09T14:34:44.186+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T14:34:44.187+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T14:34:44.188+0000] {logging_mixin.py:190} INFO - Current task name:trigger_transform state:running start_date:2025-03-09 14:34:43.557234+00:00
[2025-03-09T14:34:44.189+0000] {logging_mixin.py:190} INFO - Dag name:tiki_etl_orchestration and current dag run status:running
[2025-03-09T14:34:44.190+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T14:34:44.333+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-09 14:34:44.191430+00:00 to become allowed state ['success'] ...
[2025-03-09T14:34:54.378+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-09T14:34:54.390+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T14:34:54.391+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 14:34:43.557234+00:00 end:2025-03-09 14:34:54.389081+00:00 duration:10.831847
[2025-03-09T14:34:54.393+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_transform> dag:<DAG: tiki_etl_orchestration> dagrun:<DagRun tiki_etl_orchestration @ 2025-03-09 14:33:23.378192+00:00: manual__2025-03-09T14:33:23.378192+00:00, state:running, queued_at: 2025-03-09 14:33:23.428876+00:00. externally triggered: True>
[2025-03-09T14:34:54.394+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-09T14:34:54.395+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_etl_orchestration, task_id=trigger_transform, run_id=manual__2025-03-09T14:33:23.378192+00:00, execution_date=20250309T143323, start_date=20250309T143443, end_date=20250309T143454
[2025-03-09T14:34:54.457+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T14:34:54.458+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 181 for task trigger_transform (tiki_transform_dag failed with failed states failed; 124)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-09T14:34:54.534+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T14:34:54.582+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T14:34:54.591+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
