[2025-03-09T17:49:08.545+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T17:49:08.585+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_etl_orchestration.wait_for_extract manual__2025-03-09T17:49:03.562112+00:00 [queued]>
[2025-03-09T17:49:08.603+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_etl_orchestration.wait_for_extract manual__2025-03-09T17:49:03.562112+00:00 [queued]>
[2025-03-09T17:49:08.604+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T17:49:08.851+0000] {taskinstance.py:2890} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract> on 2025-03-09 17:49:03.562112+00:00
[2025-03-09T17:49:08.865+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T17:49:08.868+0000] {standard_task_runner.py:72} INFO - Started process 82 to run task
[2025-03-09T17:49:08.867+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_etl_orchestration', 'wait_for_extract', 'manual__2025-03-09T17:49:03.562112+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpbori4zwk']
[2025-03-09T17:49:08.869+0000] {standard_task_runner.py:105} INFO - Job 250: Subtask wait_for_extract
[2025-03-09T17:49:08.954+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_etl_orchestration.wait_for_extract manual__2025-03-09T17:49:03.562112+00:00 [running]> on host 72a6d77a3cc5
[2025-03-09T17:49:09.120+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_etl_orchestration' AIRFLOW_CTX_TASK_ID='wait_for_extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T17:49:03.562112+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T17:49:03.562112+00:00'
[2025-03-09T17:49:09.123+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T17:49:09.123+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T17:49:09.124+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_extract state:running start_date:2025-03-09 17:49:08.586133+00:00
[2025-03-09T17:49:09.125+0000] {logging_mixin.py:190} INFO - Dag name:tiki_etl_orchestration and current dag run status:running
[2025-03-09T17:49:09.126+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T17:49:09.127+0000] {baseoperator.py:423} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2025-03-09T17:49:09.146+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 309, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 289, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 254, in poke
    dttm_filter = self._get_dttm_filter(context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 243, in _get_dttm_filter
    dttm = self._handle_execution_date_fn(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 456, in _handle_execution_date_fn
    return kwargs_callable(logical_date, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 217, in kwargs_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_etl_orchestration.py", line 10, in get_execution_date
    return dt['execution_date']
           ~~^^^^^^^^^^^^^^^^^^
TypeError: 'DateTime' object is not subscriptable
[2025-03-09T17:49:09.178+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T17:49:09.179+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 17:49:08.586133+00:00 end:2025-03-09 17:49:09.177372+00:00 duration:0.591239
[2025-03-09T17:49:09.180+0000] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_for_extract> dag:<DAG: tiki_etl_orchestration> dagrun:<DagRun tiki_etl_orchestration @ 2025-03-09 17:49:03.562112+00:00: manual__2025-03-09T17:49:03.562112+00:00, state:running, queued_at: 2025-03-09 17:49:03.586362+00:00. externally triggered: True>
[2025-03-09T17:49:09.181+0000] {logging_mixin.py:190} INFO - Failure caused by 'DateTime' object is not subscriptable
[2025-03-09T17:49:09.181+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_etl_orchestration, task_id=wait_for_extract, run_id=manual__2025-03-09T17:49:03.562112+00:00, execution_date=20250309T174903, start_date=20250309T174908, end_date=20250309T174909
[2025-03-09T17:49:09.232+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T17:49:09.234+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 250 for task wait_for_extract ('DateTime' object is not subscriptable; 82)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 309, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 289, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 254, in poke
    dttm_filter = self._get_dttm_filter(context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 243, in _get_dttm_filter
    dttm = self._handle_execution_date_fn(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 456, in _handle_execution_date_fn
    return kwargs_callable(logical_date, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 217, in kwargs_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_etl_orchestration.py", line 10, in get_execution_date
    return dt['execution_date']
           ~~^^^^^^^^^^^^^^^^^^
TypeError: 'DateTime' object is not subscriptable
[2025-03-09T17:49:09.286+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T17:49:09.348+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T17:49:09.356+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
