[2025-03-10T10:17:43.214+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T10:17:43.307+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_extract_dag.crawl_laptop-may-vi-tinh-linh-kien manual__2025-03-10T10:16:46.076323+00:00 [queued]>
[2025-03-10T10:17:43.387+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_extract_dag.crawl_laptop-may-vi-tinh-linh-kien manual__2025-03-10T10:16:46.076323+00:00 [queued]>
[2025-03-10T10:17:43.389+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-10T10:17:43.509+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): crawl_laptop-may-vi-tinh-linh-kien> on 2025-03-10 10:16:46.076323+00:00
[2025-03-10T10:17:43.665+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2550) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T10:17:43.735+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_extract_dag', 'crawl_laptop-may-vi-tinh-linh-kien', 'manual__2025-03-10T10:16:46.076323+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/tiki_extract_dag.py', '--cfg-path', '/tmp/tmpfao8tcku']
[2025-03-10T10:17:43.746+0000] {standard_task_runner.py:105} INFO - Job 419: Subtask crawl_laptop-may-vi-tinh-linh-kien
[2025-03-10T10:17:43.734+0000] {standard_task_runner.py:72} INFO - Started process 2597 to run task
[2025-03-10T10:17:44.184+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_extract_dag.crawl_laptop-may-vi-tinh-linh-kien manual__2025-03-10T10:16:46.076323+00:00 [running]> on host c77555d100c4
[2025-03-10T10:19:03.418+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_extract_dag' AIRFLOW_CTX_TASK_ID='crawl_laptop-may-vi-tinh-linh-kien' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T10:16:46.076323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T10:16:46.076323+00:00'
[2025-03-10T10:19:03.430+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T10:19:03.440+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T10:19:03.494+0000] {logging_mixin.py:190} INFO - Current task name:crawl_laptop-may-vi-tinh-linh-kien state:running start_date:2025-03-10 10:17:43.313882+00:00
[2025-03-10T10:19:03.525+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag and current dag run status:running
[2025-03-10T10:19:03.527+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T10:19:57.248+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-10T10:19:57.551+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-10T10:20:07.659+0000] {job.py:229} INFO - Heartbeat recovered after 144.81 seconds
[2025-03-10T10:20:08.213+0000] {tiki_extract_dag.py:132} INFO - Starting crawl for category laptop-may-vi-tinh-linh-kien (ID: 1846)
[2025-03-10T10:20:08.215+0000] {tiki_extract_dag.py:134} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 1, 'limit': 40, 'category': '1846'}
[2025-03-10T10:20:08.999+0000] {tiki_extract_dag.py:143} INFO - Total pages for laptop-may-vi-tinh-linh-kien: 50 (limited to 50)
[2025-03-10T10:20:24.440+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 174593821: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.581+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 146012358: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.745+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 143741572: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.883+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 142459136: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.024+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 138481685: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.170+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 134561311: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.323+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 107360880: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.463+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 100625195: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.607+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 86123397: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.749+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 80799408: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.918+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 78020993: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.112+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 76283023: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.269+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 76181490: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.409+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 76054860: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.550+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 74561661: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.691+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 74547194: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.850+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 73312665: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.992+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 68828151: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.137+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 59251056: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.278+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 53080935: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.419+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 53056161: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.557+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 42561594: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.697+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 10001369: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.840+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 6910261: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.984+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 6403893: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.125+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 3054369: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.267+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 806672: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.435+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 754249: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.601+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 618526: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.741+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 511960: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.884+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 465219: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:29.059+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 416990: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:29.205+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 416978: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:29.206+0000] {tiki_extract_dag.py:156} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 2, 'limit': 40, 'category': '1846'}
[2025-03-10T10:20:29.355+0000] {tiki_extract_dag.py:178} ERROR - API error at page 2 in category laptop-may-vi-tinh-linh-kien: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:32.906+0000] {tiki_extract_dag.py:50} INFO - Updated crawled products at tiki-pipeline/tiki_crawled/crawled_products.json
[2025-03-10T10:20:32.907+0000] {tiki_extract_dag.py:192} INFO - Uploaded raw data to tiki-pipeline/raw_data/laptop-may-vi-tinh-linh-kien_20250310_102029.json, total items: 40
[2025-03-10T10:20:33.242+0000] {tiki_extract_dag.py:204} INFO - Saved metadata to tiki-pipeline/metadata/laptop-may-vi-tinh-linh-kien_extract_run_metadata_20250310_102029.json
[2025-03-10T10:20:33.243+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-10T10:20:33.260+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T10:20:33.261+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=tiki_extract_dag, task_id=crawl_laptop-may-vi-tinh-linh-kien, run_id=manual__2025-03-10T10:16:46.076323+00:00, execution_date=20250310T101646, start_date=20250310T101743, end_date=20250310T102033
[2025-03-10T10:20:33.308+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-10T10:20:33.309+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-10T10:20:33.309+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag queued_at:2025-03-10 10:16:46.133924+00:00
[2025-03-10T10:20:33.310+0000] {logging_mixin.py:190} INFO - Task hostname:c77555d100c4 operator:PythonOperator
[2025-03-10T10:20:33.356+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T10:20:33.400+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T10:20:33.405+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
