[2025-03-09T10:26:05.386+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T10:26:05.428+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T10:18:32.232485+00:00 [queued]>
[2025-03-09T10:26:05.455+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T10:18:32.232485+00:00 [queued]>
[2025-03-09T10:26:05.456+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-09T10:26:05.726+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_transform> on 2025-03-09 10:18:32.232485+00:00
[2025-03-09T10:26:05.743+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=181) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T10:26:05.747+0000] {standard_task_runner.py:72} INFO - Started process 183 to run task
[2025-03-09T10:26:05.748+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_etl_orchestration', 'trigger_transform', 'manual__2025-03-09T10:18:32.232485+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpnl375c2e']
[2025-03-09T10:26:05.750+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask trigger_transform
[2025-03-09T10:26:05.864+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_etl_orchestration.trigger_transform manual__2025-03-09T10:18:32.232485+00:00 [running]> on host 4dc18dee7126
[2025-03-09T10:26:06.032+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_etl_orchestration' AIRFLOW_CTX_TASK_ID='trigger_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T10:18:32.232485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T10:18:32.232485+00:00'
[2025-03-09T10:26:06.035+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T10:26:06.035+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T10:26:06.036+0000] {logging_mixin.py:190} INFO - Current task name:trigger_transform state:running start_date:2025-03-09 10:26:05.430071+00:00
[2025-03-09T10:26:06.037+0000] {logging_mixin.py:190} INFO - Dag name:tiki_etl_orchestration and current dag run status:running
[2025-03-09T10:26:06.038+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T10:26:06.182+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-09 10:26:06.039290+00:00 to become allowed state ['success'] ...
[2025-03-09T10:26:16.225+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-09T10:26:16.234+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T10:26:16.235+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 10:26:05.430071+00:00 end:2025-03-09 10:26:16.233888+00:00 duration:10.803817
[2025-03-09T10:26:16.237+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_transform> dag:<DAG: tiki_etl_orchestration> dagrun:<DagRun tiki_etl_orchestration @ 2025-03-09 10:18:32.232485+00:00: manual__2025-03-09T10:18:32.232485+00:00, state:running, queued_at: 2025-03-09 10:18:33.062158+00:00. externally triggered: True>
[2025-03-09T10:26:16.238+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-09T10:26:16.239+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_etl_orchestration, task_id=trigger_transform, run_id=manual__2025-03-09T10:18:32.232485+00:00, execution_date=20250309T101832, start_date=20250309T102605, end_date=20250309T102616
[2025-03-09T10:26:16.290+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T10:26:16.292+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 118 for task trigger_transform (tiki_transform_dag failed with failed states failed; 183)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-09T10:26:16.329+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T10:26:16.379+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T10:26:16.390+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
