[2025-03-10T10:17:43.131+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T10:17:43.242+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_extract_dag.crawl_thoi-trang-nam manual__2025-03-10T10:16:46.076323+00:00 [queued]>
[2025-03-10T10:17:43.291+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_extract_dag.crawl_thoi-trang-nam manual__2025-03-10T10:16:46.076323+00:00 [queued]>
[2025-03-10T10:17:43.294+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-10T10:17:43.435+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): crawl_thoi-trang-nam> on 2025-03-10 10:16:46.076323+00:00
[2025-03-10T10:17:43.480+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2555) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T10:17:43.492+0000] {standard_task_runner.py:72} INFO - Started process 2586 to run task
[2025-03-10T10:17:43.513+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_extract_dag', 'crawl_thoi-trang-nam', 'manual__2025-03-10T10:16:46.076323+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/tiki_extract_dag.py', '--cfg-path', '/tmp/tmpu8_nmc2w']
[2025-03-10T10:17:43.538+0000] {standard_task_runner.py:105} INFO - Job 415: Subtask crawl_thoi-trang-nam
[2025-03-10T10:17:44.099+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_extract_dag.crawl_thoi-trang-nam manual__2025-03-10T10:16:46.076323+00:00 [running]> on host c77555d100c4
[2025-03-10T10:18:38.283+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_extract_dag' AIRFLOW_CTX_TASK_ID='crawl_thoi-trang-nam' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T10:16:46.076323+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T10:16:46.076323+00:00'
[2025-03-10T10:18:38.286+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T10:18:38.287+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T10:18:38.288+0000] {logging_mixin.py:190} INFO - Current task name:crawl_thoi-trang-nam state:running start_date:2025-03-10 10:17:43.246341+00:00
[2025-03-10T10:18:38.290+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag and current dag run status:running
[2025-03-10T10:18:38.292+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T10:19:00.946+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5228ea7920>: Failed to resolve 'oauth2.googleapis.com' ([Errno -3] Temporary failure in name resolution)")': /token
[2025-03-10T10:19:03.513+0000] {job.py:229} INFO - Heartbeat recovered after 80.70 seconds
[2025-03-10T10:19:57.267+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 233, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 284, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2360, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 873, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2346, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-10T10:19:57.495+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-10T10:20:02.808+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5228c13f20>: Failed to resolve 'oauth2.googleapis.com' ([Errno -3] Temporary failure in name resolution)")': /token
[2025-03-10T10:20:07.129+0000] {job.py:229} INFO - Heartbeat recovered after 63.75 seconds
[2025-03-10T10:20:08.266+0000] {tiki_extract_dag.py:132} INFO - Starting crawl for category thoi-trang-nam (ID: 915)
[2025-03-10T10:20:08.273+0000] {tiki_extract_dag.py:134} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 1, 'limit': 40, 'category': '915'}
[2025-03-10T10:20:09.640+0000] {tiki_extract_dag.py:143} INFO - Total pages for thoi-trang-nam: 50 (limited to 50)
[2025-03-10T10:20:23.712+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 154298071: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:23.873+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 145680551: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.016+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 133821238: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.189+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 126700166: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.344+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 126146318: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.486+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 124635780: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.627+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 111972654: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.786+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 109403033: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:24.951+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 107186342: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.090+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 104312787: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.247+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 104080625: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.391+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 103076103: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.532+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 99968881: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.673+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 99958075: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.822+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 95052893: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:25.974+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 88011606: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.130+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 87981660: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.295+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 79435123: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.434+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 76537581: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.574+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 75329276: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.736+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 68573034: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:26.896+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 56614642: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.038+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 52189164: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.182+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 52184516: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.322+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 35087712: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.482+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 31638135: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.620+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 31637590: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.791+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 16712370: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:27.955+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 14694284: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.116+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 9730171: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.281+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 7599073: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.422+0000] {tiki_extract_dag.py:119} ERROR - Error fetching details for product 4965821: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:28.424+0000] {tiki_extract_dag.py:156} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 2, 'limit': 40, 'category': '915'}
[2025-03-10T10:20:28.564+0000] {tiki_extract_dag.py:178} ERROR - API error at page 2 in category thoi-trang-nam: Expecting value: line 1 column 1 (char 0)
[2025-03-10T10:20:31.802+0000] {tiki_extract_dag.py:50} INFO - Updated crawled products at tiki-pipeline/tiki_crawled/crawled_products.json
[2025-03-10T10:20:31.803+0000] {tiki_extract_dag.py:192} INFO - Uploaded raw data to tiki-pipeline/raw_data/thoi-trang-nam_20250310_102028.json, total items: 40
[2025-03-10T10:20:32.141+0000] {tiki_extract_dag.py:204} INFO - Saved metadata to tiki-pipeline/metadata/thoi-trang-nam_extract_run_metadata_20250310_102028.json
[2025-03-10T10:20:32.145+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-10T10:20:32.293+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T10:20:32.297+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=tiki_extract_dag, task_id=crawl_thoi-trang-nam, run_id=manual__2025-03-10T10:16:46.076323+00:00, execution_date=20250310T101646, start_date=20250310T101743, end_date=20250310T102032
[2025-03-10T10:20:32.414+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-10T10:20:32.415+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-10T10:20:32.416+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag queued_at:2025-03-10 10:16:46.133924+00:00
[2025-03-10T10:20:32.417+0000] {logging_mixin.py:190} INFO - Task hostname:c77555d100c4 operator:PythonOperator
[2025-03-10T10:20:32.471+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T10:20:32.541+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T10:20:32.546+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
