[2025-03-12T07:26:10.529+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T07:26:10.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_extract_dag.extract_sach manual__2025-03-12T07:25:54.854919+00:00 [queued]>
[2025-03-12T07:26:10.615+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_extract_dag.extract_sach manual__2025-03-12T07:25:54.854919+00:00 [queued]>
[2025-03-12T07:26:10.616+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-12T07:26:10.663+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_sach> on 2025-03-12 07:25:54.854919+00:00
[2025-03-12T07:26:10.717+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=217) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T07:26:10.729+0000] {standard_task_runner.py:72} INFO - Started process 252 to run task
[2025-03-12T07:26:10.729+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_extract_dag', 'extract_sach', 'manual__2025-03-12T07:25:54.854919+00:00', '--job-id', '674', '--raw', '--subdir', 'DAGS_FOLDER/tiki_extract_dag.py', '--cfg-path', '/tmp/tmpk26xhlx2']
[2025-03-12T07:26:10.744+0000] {standard_task_runner.py:105} INFO - Job 674: Subtask extract_sach
[2025-03-12T07:26:11.124+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_extract_dag.extract_sach manual__2025-03-12T07:25:54.854919+00:00 [running]> on host 3905098656d4
[2025-03-12T07:26:15.583+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_extract_dag' AIRFLOW_CTX_TASK_ID='extract_sach' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T07:25:54.854919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T07:25:54.854919+00:00'
[2025-03-12T07:26:15.594+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T07:26:15.596+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T07:26:15.597+0000] {logging_mixin.py:190} INFO - Current task name:extract_sach state:running start_date:2025-03-12 07:26:10.581837+00:00
[2025-03-12T07:26:15.598+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag and current dag run status:running
[2025-03-12T07:26:15.600+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T07:26:18.441+0000] {tiki_extract_dag.py:122} INFO - Starting crawl for category sach
[2025-03-12T07:26:19.656+0000] {tiki_extract_dag.py:129} INFO - Total pages for sach: 50
[2025-03-12T07:26:21.918+0000] {tiki_extract_dag.py:155} INFO - Extracted page 2/50 - sach, total items: 80
[2025-03-12T07:26:30.123+0000] {tiki_extract_dag.py:155} INFO - Extracted page 3/50 - sach, total items: 120
[2025-03-12T07:26:39.904+0000] {tiki_extract_dag.py:155} INFO - Extracted page 4/50 - sach, total items: 160
[2025-03-12T07:26:48.500+0000] {tiki_extract_dag.py:155} INFO - Extracted page 5/50 - sach, total items: 200
[2025-03-12T07:26:56.011+0000] {tiki_extract_dag.py:155} INFO - Extracted page 6/50 - sach, total items: 240
[2025-03-12T07:27:03.554+0000] {tiki_extract_dag.py:155} INFO - Extracted page 7/50 - sach, total items: 280
[2025-03-12T07:27:14.426+0000] {tiki_extract_dag.py:155} INFO - Extracted page 8/50 - sach, total items: 320
[2025-03-12T07:27:24.156+0000] {tiki_extract_dag.py:155} INFO - Extracted page 9/50 - sach, total items: 360
[2025-03-12T07:27:30.794+0000] {tiki_extract_dag.py:155} INFO - Extracted page 10/50 - sach, total items: 400
[2025-03-12T07:27:37.449+0000] {tiki_extract_dag.py:155} INFO - Extracted page 11/50 - sach, total items: 440
[2025-03-12T07:27:45.639+0000] {tiki_extract_dag.py:155} INFO - Extracted page 12/50 - sach, total items: 480
[2025-03-12T07:27:55.452+0000] {tiki_extract_dag.py:155} INFO - Extracted page 13/50 - sach, total items: 520
[2025-03-12T07:28:01.316+0000] {tiki_extract_dag.py:155} INFO - Extracted page 14/50 - sach, total items: 560
[2025-03-12T07:28:10.914+0000] {tiki_extract_dag.py:155} INFO - Extracted page 15/50 - sach, total items: 600
[2025-03-12T07:28:18.497+0000] {tiki_extract_dag.py:155} INFO - Extracted page 16/50 - sach, total items: 640
[2025-03-12T07:28:28.442+0000] {tiki_extract_dag.py:155} INFO - Extracted page 17/50 - sach, total items: 680
[2025-03-12T07:28:38.153+0000] {tiki_extract_dag.py:155} INFO - Extracted page 18/50 - sach, total items: 720
[2025-03-12T07:28:46.807+0000] {tiki_extract_dag.py:155} INFO - Extracted page 19/50 - sach, total items: 760
[2025-03-12T07:28:56.972+0000] {tiki_extract_dag.py:155} INFO - Extracted page 20/50 - sach, total items: 800
[2025-03-12T07:29:05.238+0000] {tiki_extract_dag.py:155} INFO - Extracted page 21/50 - sach, total items: 840
[2025-03-12T07:29:12.562+0000] {tiki_extract_dag.py:155} INFO - Extracted page 22/50 - sach, total items: 880
[2025-03-12T07:29:21.175+0000] {tiki_extract_dag.py:155} INFO - Extracted page 23/50 - sach, total items: 920
[2025-03-12T07:29:28.448+0000] {tiki_extract_dag.py:155} INFO - Extracted page 24/50 - sach, total items: 960
[2025-03-12T07:29:37.266+0000] {tiki_extract_dag.py:155} INFO - Extracted page 25/50 - sach, total items: 1000
[2025-03-12T07:29:44.648+0000] {tiki_extract_dag.py:155} INFO - Extracted page 26/50 - sach, total items: 1040
[2025-03-12T07:29:53.819+0000] {tiki_extract_dag.py:155} INFO - Extracted page 27/50 - sach, total items: 1080
[2025-03-12T07:30:02.419+0000] {tiki_extract_dag.py:155} INFO - Extracted page 28/50 - sach, total items: 1120
[2025-03-12T07:30:10.830+0000] {tiki_extract_dag.py:155} INFO - Extracted page 29/50 - sach, total items: 1160
[2025-03-12T07:30:19.185+0000] {tiki_extract_dag.py:155} INFO - Extracted page 30/50 - sach, total items: 1200
[2025-03-12T07:30:27.747+0000] {tiki_extract_dag.py:155} INFO - Extracted page 31/50 - sach, total items: 1240
[2025-03-12T07:30:36.385+0000] {tiki_extract_dag.py:155} INFO - Extracted page 32/50 - sach, total items: 1280
[2025-03-12T07:30:44.952+0000] {tiki_extract_dag.py:155} INFO - Extracted page 33/50 - sach, total items: 1320
[2025-03-12T07:30:52.766+0000] {tiki_extract_dag.py:155} INFO - Extracted page 34/50 - sach, total items: 1360
[2025-03-12T07:31:01.600+0000] {tiki_extract_dag.py:155} INFO - Extracted page 35/50 - sach, total items: 1400
[2025-03-12T07:31:10.446+0000] {tiki_extract_dag.py:155} INFO - Extracted page 36/50 - sach, total items: 1440
[2025-03-12T07:31:20.439+0000] {tiki_extract_dag.py:155} INFO - Extracted page 37/50 - sach, total items: 1480
[2025-03-12T07:31:28.206+0000] {tiki_extract_dag.py:155} INFO - Extracted page 38/50 - sach, total items: 1520
[2025-03-12T07:31:37.227+0000] {tiki_extract_dag.py:155} INFO - Extracted page 39/50 - sach, total items: 1560
[2025-03-12T07:31:44.627+0000] {tiki_extract_dag.py:155} INFO - Extracted page 40/50 - sach, total items: 1600
[2025-03-12T07:31:55.329+0000] {tiki_extract_dag.py:155} INFO - Extracted page 41/50 - sach, total items: 1640
[2025-03-12T07:32:05.662+0000] {tiki_extract_dag.py:155} INFO - Extracted page 42/50 - sach, total items: 1680
[2025-03-12T07:32:12.719+0000] {tiki_extract_dag.py:155} INFO - Extracted page 43/50 - sach, total items: 1720
[2025-03-12T07:32:20.230+0000] {tiki_extract_dag.py:155} INFO - Extracted page 44/50 - sach, total items: 1760
[2025-03-12T07:32:29.358+0000] {tiki_extract_dag.py:155} INFO - Extracted page 45/50 - sach, total items: 1800
[2025-03-12T07:32:36.381+0000] {tiki_extract_dag.py:155} INFO - Extracted page 46/50 - sach, total items: 1840
[2025-03-12T07:32:45.308+0000] {tiki_extract_dag.py:155} INFO - Extracted page 47/50 - sach, total items: 1880
[2025-03-12T07:32:52.228+0000] {tiki_extract_dag.py:155} INFO - Extracted page 48/50 - sach, total items: 1920
[2025-03-12T07:33:00.485+0000] {tiki_extract_dag.py:155} INFO - Extracted page 49/50 - sach, total items: 1960
[2025-03-12T07:33:10.543+0000] {tiki_extract_dag.py:155} INFO - Extracted page 50/50 - sach, total items: 2000
[2025-03-12T07:33:32.580+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 186, in __call__
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_extract_dag.py", line 170, in extract_category_data
    blob.upload_from_string(json.dumps(all_raw_data), content_type='application/json')
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 3128, in upload_from_string
    self.upload_from_file(
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2851, in upload_from_file
    self._prep_and_do_upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2700, in _prep_and_do_upload
    created_json = self._do_upload(
                   ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2506, in _do_upload
    response = self._do_multipart_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2007, in _do_multipart_upload
    response = upload.transmit(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 145, in retriable_request
    result = transport.request(
             ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 533, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
               ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-12T07:33:32.713+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-12T07:33:32.714+0000] {logging_mixin.py:190} INFO - Task start:2025-03-12 07:26:10.581837+00:00 end:2025-03-12 07:33:32.706147+00:00 duration:442.12431
[2025-03-12T07:33:32.716+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_sach> dag:<DAG: tiki_extract_dag> dagrun:<DagRun tiki_extract_dag @ 2025-03-12 07:25:54.854919+00:00: manual__2025-03-12T07:25:54.854919+00:00, state:running, queued_at: 2025-03-12 07:25:54.899816+00:00. externally triggered: True>
[2025-03-12T07:33:32.717+0000] {logging_mixin.py:190} INFO - Failure caused by ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-12T07:33:32.718+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_extract_dag, task_id=extract_sach, run_id=manual__2025-03-12T07:25:54.854919+00:00, execution_date=20250312T072554, start_date=20250312T072610, end_date=20250312T073332
[2025-03-12T07:33:32.837+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T07:33:32.839+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 674 for task extract_sach (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 252)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1430, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 186, in __call__
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_extract_dag.py", line 170, in extract_category_data
    blob.upload_from_string(json.dumps(all_raw_data), content_type='application/json')
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 3128, in upload_from_string
    self.upload_from_file(
  File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2851, in upload_from_file
    self._prep_and_do_upload(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2700, in _prep_and_do_upload
    created_json = self._do_upload(
                   ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2506, in _do_upload
    response = self._do_multipart_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/storage/blob.py", line 2007, in _do_multipart_upload
    response = upload.transmit(
               ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 145, in retriable_request
    result = transport.request(
             ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 533, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/credentials.py", line 239, in before_request
    self._blocking_refresh(request)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/credentials.py", line 202, in _blocking_refresh
    self.refresh(request)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/oauth2/_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
               ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/auth/transport/requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-12T07:33:32.914+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-12T07:33:33.020+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T07:33:33.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
