[2025-03-11T14:27:46.066+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T14:27:46.138+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_extract_dag.crawl_dien-tu-dien-lanh manual__2025-03-11T14:07:26.849945+00:00 [queued]>
[2025-03-11T14:27:46.183+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_extract_dag.crawl_dien-tu-dien-lanh manual__2025-03-11T14:07:26.849945+00:00 [queued]>
[2025-03-11T14:27:46.184+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 4
[2025-03-11T14:27:46.244+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): crawl_dien-tu-dien-lanh> on 2025-03-11 14:07:26.849945+00:00
[2025-03-11T14:27:46.287+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2394) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T14:27:46.296+0000] {standard_task_runner.py:72} INFO - Started process 2403 to run task
[2025-03-11T14:27:46.300+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_extract_dag', 'crawl_dien-tu-dien-lanh', 'manual__2025-03-11T14:07:26.849945+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/tiki_extract_dag.py', '--cfg-path', '/tmp/tmpxwj_18vw']
[2025-03-11T14:27:46.304+0000] {standard_task_runner.py:105} INFO - Job 604: Subtask crawl_dien-tu-dien-lanh
[2025-03-11T14:27:46.448+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_extract_dag.crawl_dien-tu-dien-lanh manual__2025-03-11T14:07:26.849945+00:00 [running]> on host 5c8190d7da62
[2025-03-11T14:27:49.500+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_extract_dag' AIRFLOW_CTX_TASK_ID='crawl_dien-tu-dien-lanh' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T14:07:26.849945+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T14:07:26.849945+00:00'
[2025-03-11T14:27:49.502+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T14:27:49.504+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T14:27:49.505+0000] {logging_mixin.py:190} INFO - Current task name:crawl_dien-tu-dien-lanh state:running start_date:2025-03-11 14:27:46.140044+00:00
[2025-03-11T14:27:49.505+0000] {logging_mixin.py:190} INFO - Dag name:tiki_extract_dag and current dag run status:running
[2025-03-11T14:27:49.506+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T14:27:53.076+0000] {tiki_extract_dag.py:139} INFO - Starting crawl for category dien-tu-dien-lanh (ID: 4221)
[2025-03-11T14:27:53.077+0000] {tiki_extract_dag.py:141} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 1, 'limit': 40, 'category': '4221'}
[2025-03-11T14:27:54.055+0000] {tiki_extract_dag.py:150} INFO - Total pages for dien-tu-dien-lanh: 50 (limited to 50)
[2025-03-11T14:27:56.109+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 275975448 on attempt 1/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:28:04.232+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 275975448 on attempt 2/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:28:26.866+0000] {tiki_extract_dag.py:163} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 2, 'limit': 40, 'category': '4221'}
[2025-03-11T14:28:40.261+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 91272453 on attempt 1/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:28:46.782+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 91272453 on attempt 2/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:28:53.986+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 91272453 on attempt 3/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:28:54.171+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 85376469 on attempt 1/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:29:01.864+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 85376469 on attempt 2/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:29:11.849+0000] {tiki_extract_dag.py:183} INFO - Extracted page 2/50 for category dien-tu-dien-lanh, total items: 80
[2025-03-11T14:29:30.828+0000] {tiki_extract_dag.py:163} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 3, 'limit': 40, 'category': '4221'}
[2025-03-11T14:29:45.392+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 100087607 on attempt 1/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:29:53.072+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 100087607 on attempt 2/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:29:59.497+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 100087607 on attempt 3/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:29:59.728+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 94857614 on attempt 1/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:30:13.600+0000] {tiki_extract_dag.py:183} INFO - Extracted page 3/50 for category dien-tu-dien-lanh, total items: 120
[2025-03-11T14:30:28.731+0000] {tiki_extract_dag.py:163} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 4, 'limit': 40, 'category': '4221'}
[2025-03-11T14:30:41.564+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 56713023 on attempt 1/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:30:50.675+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 56713023 on attempt 2/3: Expecting value: line 1 column 1 (char 0)
[2025-03-11T14:30:58.977+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729bb5acf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products/56713023
[2025-03-11T14:31:01.017+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729babab40>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products/56713023
[2025-03-11T14:31:13.057+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729baba570>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products/56713023
[2025-03-11T14:31:21.163+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729ba9cef0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/56713023
[2025-03-11T14:31:37.182+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae0a70>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/56713023
[2025-03-11T14:31:37.210+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 56713023 on attempt 3/3: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products/56713023 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae0ec0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)"))
[2025-03-11T14:31:37.228+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729babb290>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:31:39.230+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae0a10>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:31:43.236+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae1220>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:31:51.253+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae1640>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:07.260+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae1880>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:07.286+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 54020025 on attempt 1/3: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products/54020025 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae1b80>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)"))
[2025-03-11T14:32:17.432+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae21b0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:19.707+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae2390>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:23.722+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729ba9d400>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:31.744+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729babb380>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:47.775+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729babb6b0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:47.806+0000] {tiki_extract_dag.py:120} ERROR - Error fetching details for product 54020025 on attempt 2/3: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products/54020025 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bab9f40>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)"))
[2025-03-11T14:32:57.524+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae2030>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:32:59.543+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae03e0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:33:03.565+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae0ec0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:33:11.637+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae0170>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:33:27.656+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae23c0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products/54020025
[2025-03-11T14:33:32.881+0000] {tiki_extract_dag.py:183} INFO - Extracted page 4/50 for category dien-tu-dien-lanh, total items: 160
[2025-03-11T14:33:49.890+0000] {tiki_extract_dag.py:163} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 5, 'limit': 40, 'category': '4221'}
[2025-03-11T14:34:04.438+0000] {tiki_extract_dag.py:183} INFO - Extracted page 5/50 for category dien-tu-dien-lanh, total items: 200
[2025-03-11T14:34:21.615+0000] {tiki_extract_dag.py:163} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 6, 'limit': 40, 'category': '4221'}
[2025-03-11T14:34:28.984+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729bae2690>: Failed to resolve 'tiki.vn' ([Errno -5] No address associated with hostname)")': /api/v2/products?page=6&limit=40&category=4221
[2025-03-11T14:34:31.018+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b92c7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=6&limit=40&category=4221
[2025-03-11T14:34:35.035+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b92c620>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=6&limit=40&category=4221
[2025-03-11T14:34:43.063+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b92ccb0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=6&limit=40&category=4221
[2025-03-11T14:35:01.106+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b92cef0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=6&limit=40&category=4221
[2025-03-11T14:35:31.320+0000] {tiki_extract_dag.py:183} INFO - Extracted page 6/50 for category dien-tu-dien-lanh, total items: 240
[2025-03-11T14:35:50.331+0000] {tiki_extract_dag.py:163} INFO - Calling API: https://tiki.vn/api/v2/products with params: {'page': 7, 'limit': 40, 'category': '4221'}
[2025-03-11T14:35:50.379+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b92d1c0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:35:52.390+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b95e270>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:35:57.381+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b95c380>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:36:05.420+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=1, connect=1, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b95fa10>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:36:23.455+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=0, connect=0, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f729b95fdd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:36:23.496+0000] {tiki_extract_dag.py:186} ERROR - API error at page 7 in category dien-tu-dien-lanh on attempt 1/3: HTTPSConnectionPool(host='tiki.vn', port=443): Max retries exceeded with url: /api/v2/products?page=7&limit=40&category=4221 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729b95ffb0>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)"))
[2025-03-11T14:36:31.870+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729b968350>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:36:33.955+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=3, connect=3, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729b968740>: Failed to resolve 'tiki.vn' ([Errno -2] Name or service not known)")': /api/v2/products?page=7&limit=40&category=4221
[2025-03-11T14:36:45.965+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=2, read=5, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f729b968890>: Failed to resolve 'tiki.vn' ([Errno -3] Temporary failure in name resolution)")': /api/v2/products?page=7&limit=40&category=4221
