[2025-03-10T08:10:07.055+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T08:10:07.077+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_schema manual__2025-03-10T08:03:57.149567+00:00 [queued]>
[2025-03-10T08:10:07.088+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_schema manual__2025-03-10T08:03:57.149567+00:00 [queued]>
[2025-03-10T08:10:07.089+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-10T08:10:07.248+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_schema> on 2025-03-10 08:03:57.149567+00:00
[2025-03-10T08:10:07.257+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=625) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T08:10:07.259+0000] {standard_task_runner.py:72} INFO - Started process 627 to run task
[2025-03-10T08:10:07.259+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_orchestration_dag', 'trigger_schema', 'manual__2025-03-10T08:03:57.149567+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpkf1nj29i']
[2025-03-10T08:10:07.260+0000] {standard_task_runner.py:105} INFO - Job 328: Subtask trigger_schema
[2025-03-10T08:10:07.308+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_orchestration_dag.trigger_schema manual__2025-03-10T08:03:57.149567+00:00 [running]> on host c77555d100c4
[2025-03-10T08:10:07.399+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_orchestration_dag' AIRFLOW_CTX_TASK_ID='trigger_schema' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T08:03:57.149567+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T08:03:57.149567+00:00'
[2025-03-10T08:10:07.400+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T08:10:07.401+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T08:10:07.401+0000] {logging_mixin.py:190} INFO - Current task name:trigger_schema state:running start_date:2025-03-10 08:10:07.078524+00:00
[2025-03-10T08:10:07.402+0000] {logging_mixin.py:190} INFO - Dag name:tiki_orchestration_dag and current dag run status:running
[2025-03-10T08:10:07.402+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T08:10:07.466+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_schema_management_dag on 2025-03-10 08:10:07.402967+00:00 to become allowed state ['success'] ...
[2025-03-10T08:11:07.485+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_schema_management_dag failed with failed states failed
[2025-03-10T08:11:07.490+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T08:11:07.491+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 08:10:07.078524+00:00 end:2025-03-10 08:11:07.489964+00:00 duration:60.41144
[2025-03-10T08:11:07.491+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_schema> dag:<DAG: tiki_orchestration_dag> dagrun:<DagRun tiki_orchestration_dag @ 2025-03-10 08:03:57.149567+00:00: manual__2025-03-10T08:03:57.149567+00:00, state:running, queued_at: 2025-03-10 08:03:57.334541+00:00. externally triggered: True>
[2025-03-10T08:11:07.492+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_schema_management_dag failed with failed states failed
[2025-03-10T08:11:07.492+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_orchestration_dag, task_id=trigger_schema, run_id=manual__2025-03-10T08:03:57.149567+00:00, execution_date=20250310T080357, start_date=20250310T081007, end_date=20250310T081107
[2025-03-10T08:11:07.520+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T08:11:07.520+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 328 for task trigger_schema (tiki_schema_management_dag failed with failed states failed; 627)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_schema_management_dag failed with failed states failed
[2025-03-10T08:11:07.554+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T08:11:07.579+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T08:11:07.584+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
